<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "blog".
 *
 * @property int $id
 * @property string $title
 * @property string|null $text
 * @property string $url
 * @property int $status_id
 * @property int $sort
 */
class Blog extends \yii\db\ActiveRecord
{
    public $tags_array;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'url'], 'required'],
            [['text'], 'string'],
            [['url'], 'unique'],
            [['status_id', 'sort'], 'integer'],
            [['sort'], 'integer', 'max' => 99, 'min' => 1],
            [['title', 'url'], 'string', 'max' => 150],
            [['tags_array'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'text' => 'Текст',
            'url' => 'ЧПУ',
            'status_id' => 'Статус',
            'sort' => 'Сортировка',
            'tags_array' => 'Тэги',
            'tagsAsString' => 'Tэги данного поста',
            'author.username' => 'Имя автора'
        ];
    }

    public static function getStatusList()
    {
        return ['off', 'on'];
    }

    public function getStatusName()
    {
        $list = self::getStatusList();
        return $list[$this->status_id];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getTagsAsString()
    {
        $arr = ArrayHelper::map($this->tags, 'name', 'name');
        return implode(', ', $arr);
    }

    public function getBlogTag()
    {
        return $this->hasMany(BlogTag::className(), ['blog_id' => 'id']);
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->via('blogTag');
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->tags_array = ArrayHelper::map($this->tags, 'name', 'name');
    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
//        $arr = ArrayHelper::map($this->tags, 'id', 'id');
//        if (is_array($this->tags_array)) {
//            foreach ($this->tags_array as $one) {
//                if (!in_array($one, $arr)) {
//                    $this->createNewTag($one);
//                    $model = new BlogTag();
//                    $model->blog_id = $this->id;
//                    $model->tag_id = $one;
//                    $model->save();
//
//                }
//                if (isset($arr[$one])) {
//                    unset($arr[$one]);
//                }
//            }
//            BlogTag::deleteAll(['tag_id' => $arr, 'blog_id' => $this->id]);
//        } else {
//            BlogTag::deleteAll(['tag_id' => $arr, 'blog_id' => $this->id]);
//        }}
        if (is_array($this->tags_array)){
            $old_tags=ArrayHelper::map($this->tags,'name','id');
            foreach ($this->tags_array as $one_new_tag) {
                if (isset($old_tags[$one_new_tag])) {
                    unset($old_tags[$one_new_tag]);
                }
                else {
                    $this->createNewTag($one_new_tag);
                }
            }
                BlogTag::deleteAll(['and',['blog_id'=>$this->id],['tag_id'=>$old_tags]]);
            }else{
                BlogTag::deleteAll(['blog_id'=>$this->id]);
            }
        }


        private function createNewTag($one_new_tag)
        {
            if (!$tag = Tag::find()->andWhere(['name' => $one_new_tag])->one()) {
                $tag = new Tag();
                $tag->name = $one_new_tag;
                if (!$tag->save()) {
                    $tag = null;
                }
            }
            if ($tag instanceof Tag) {
                $blog_tag = new BlogTag();
                $blog_tag->blog_id = $this->id;
                $blog_tag->tag_id = $tag->id;
                if ($blog_tag->save()) {
                    return $blog_tag->id;
                }
                return false;
            }
        }

    }

